name: "✨ Feature request"
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature! Please help us understand the problem and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your idea. Include UI/UX notes if relevant.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've thought about
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks / trade-offs
      description: Performance, permissions, security, cross-browser considerations
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, or references
    validations:
      required: false


